apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solidarytech
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Krohanar/hackathon-DCLT.git
    targetRevision: fase-5-implementacao
    path: k8s/base

  destination:
    server: https://kubernetes.default.svc
    namespace: solidarytech

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
